# -*- coding: utf-8 -*-
"""Meeting Minutes Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJONPLMN8QhY91PiQoQCadLwkhgtlydU
"""

import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATIOR\n")
#user inputs
meeting_title = input("enter meeting title: ")
date = input("enter meeting date (DD-MM-YYYY): ")
time = input("enter meeting time: ")
participants = input(" enter participants (comma seperated): ")
agenda = input("enter agenda points (comma separeted): ")
decision = input("enter decision points (comma seperated): ")
action_items = input("enter action items (comma seperated): ")
prepared_by = input("prepared by: ")
#process Inputs
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decision_list = [d.strip() for d in decision.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]
# create structured meeting minutes
minutes = {
    "Meeting title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda":"; ".join(agenda_list),
    "Decision":"; ".join(decision_list),
    "Action Items":"; ".join(actions_list),
    "Prepared By": prepared_by,
    "Generation On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}
#convert to datasFrame
df = pd.DataFrame(list(minutes.items()), columns=["field", "Details"])
print("\n meeting minutes generated successfully\n")
display(df)
#save as CSV
df.to_csv("meeting_minutes.csv", index=False)
print("\n file saved as meeting_minutes.csv")