# -*- coding: utf-8 -*-
"""similarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGUooGar0_KEgK-rv3-gM0m1mMH-KxmW
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

#load the model
model = SentenceTransformer('all-MiniLM-L6-v2')

#Take inputfrom user
text1=input("Enter Text 1: ")
text2=input("Enter Text 2: ")

#convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)

#calculate similarity
similarity=util.cos_sim(embedding1, embedding2)

#show result
print("\nSimilarity Score:", round(float(similarity),2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")